export const FETCH_BREEDS_START = 'FETCH_BREEDS_START';
export const FETCH_BREEDS_SUCCESS = 'FETCH_BREEDS_SUCCESS';
export const FETCH_BREEDS_FAIL = 'FETCH_BREEDS_FAIL';

export const FETCH_BY_BREED_START = 'FETCH_BY_BREED_START';
export const FETCH_BY_BREED_SUCCESS = 'FETCH_BY_BREED_SUCCESS';
export const FETCH_BY_BREED_FAIL = 'FETCH_BY_BREED_FAIL';

export const FETCH_RANDOM_DOG_BY_BREED_START = 'FETCH_RANDOM_DOG_BY_BREED_START';
export const FETCH_RANDOM_DOG_BY_BREED_SUCCESS = 'FETCH_RANDOM_DOG_BY_BREED_SUCCESS';
export const FETCH_RANDOM_DOG_BY_BREED_FAIL = 'FETCH_RANDOM_DOG_BY_BREED_FAIL';